base_model: Qwen/Qwen2.5-3B
# Automatically upload checkpoint and final model to HF
#hub_model_id: mohit5tech9999/first_trained_sft
shuffle_merged_datasets: false
load_in_8bit: false
load_in_4bit: false
strict: false
chat_template: chatml
datasets:
  - path: json
    ds_type: json
    split: train
    type: chat_template
    data_files:
      - data/dolphi-r1-nonreasoning_90.jsonl
      - data/dolphin-r1-flash-reasoning_90.jsonl
      - data/dolphin-r1-deepseek-reasoning_90.jsonl
      - data/final_response_synth_90.jsonl
      - data/function_calling_synth_90.jsonl
      - data/mix.jsonl
    trust_remote_code: True
dataset_prepared_path: /shared/last_run_prepared
val_set_size: 0.05
output_dir: ./outputs/furst_trained_sft

sequence_len: 16384
sample_packing: true
pad_to_sequence_len: true

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 1
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 2e-5

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 1
xformers_attention:
flash_attention: True
deepspeed: deepspeed_configs/zero3_bf16_cpuoffload_params.json
warmup_steps: 100
evals_per_epoch: 2
eval_table_size:
saves_per_epoch: 1
debug:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: <|end_of_text|>
   