adapter: qlora
base_model: meta-llama/Llama-2-7b-hf
bf16: auto
dataset_prepared_path: null
datasets:
- path: mohit9999/all_news_finance_sm_1h2023_custom
  type: alpaca
debug: null
deepspeed: null
early_stopping_patience: null
eval_sample_packing: true
eval_table_size: null
evals_per_epoch: 1
flash_attention: false
fp16: null
fsdp: null
fsdp_config: null
gradient_accumulation_steps: 2
gradient_checkpointing: true
group_by_length: false
hub_model_id: mohit9999/all_news_finance_sm_1h2023_custom_model_3
learning_rate: 2e-5
load_in_4bit: true
load_in_8bit: false
logging_steps: 1
lora_alpha: 16
lora_dropout: 0.05
lora_fan_in_fan_out: null
lora_model_dir: null
lora_modules_to_save:
- embed_tokens
- lm_head
lora_r: 32
lora_target_linear: true
lr_scheduler: cosine
max_steps: 25
micro_batch_size: 1
model_type: LlamaForCausalLM
num_epochs: 1
optimizer: paged_adamw_8bit
output_dir: ./outputs/lora-out-3
pad_to_sequence_len: true
resume_from_checkpoint: null
sample_packing: true
saves_per_epoch: 1
sdp_attention: true
sequence_len: 2048
special_tokens: null
strict: false
tf32: false
tokenizer_type: LlamaTokenizer
train_on_inputs: false
val_set_size: 0.05
wandb_entity: null
wandb_log_model: null
wandb_name: null
wandb_project: null
wandb_watch: null
warmup_steps: 1
weight_decay: 0.0
xformers_attention: null
